EVENT_SPENDINGS = ["asdad", "asd", "qe"]
EVENT_DATES = ["qew", "qwwww", "ee"]
EVENT_REASONS = ["ddd", "qew", "hhh"]
    
TICKET_SPENDINGS = []
TICKET_DATES_ARIVE = []
TICKET_DATES_COMEBACK = []
TICKET_RACES_ID = []
TICKET_HOMES = []
TICKET_AWAYS = []
